local l = {}

l.textGroups = {
	mainMenu = {
		chartCount = "You have %i charts available!",
		sessionTime = "Game has been running for %s",
		time = "It is currently %s",
		supporter = "Thank you for playing soundsphere!"
	},
	settings = {
		-------------- General
		general = "GENERAL",
		-- Language
		language = "LANGUAGE",
		selectLanguage = "Select language:",
		originalMetadata = "Prefer metadata in original language",
		-- Updates
		updates = "UPDATES",
		autoUpdate = "Update game automatically",
		gitVersion = "Git version of the game.",
		upToDate = "Your soundsphere is up-to-date!",
		notUpToDate = "Cannot tell if the game is up to date.",
		openSoundsphereFolder = "Open soundsphere folder",
		--- Song select
		songSelect = "SONG SELECT",
		difficultyCalculator = "Difficulty calculator:",
		vimMotions = "Vim motions (ONLY FOR EXPERTS)",
		previewIcon = "Preview icon (Only shifts text)",
		chartPreview = "Chart preview",
		backgroundDim = "Background dim:",
		backgroundBlur = "Background blur:",
		preciseRates = "0.025x Music speed increment",
		preciseRatesTip = "Allows music speed to be increased by 0.025x instead of 0.05x.",
		--- Result screen
		resultScreen = "RESULT SCREEN",
		showDifficultyAndRate = "Show difficulty and rate",
		showHitGraph = "Show hit graph",
		showPP = "Show PP",
		-------------- Graphics
		graphics = "GRAPHICS",
		-- Renderer
		renderer = "RENDERER",
		vsyncType = "Vsync type:",
		fpsLimit = "FPS limit:",
		showFPS = "Show FPS",
		showProfiler = "Show profiler",
		vsyncInSongSelect = "Vsync in Song Select",
		adaptive = "Adaptive",
		enabled = "Enabled",
		disabled = "Disabled",
		msaaTip = "Antialiasing. Set this option to 2 or 4 to eliminate sharp edges on the screen. Game restart required.",
		dwmFlushTip = "Acts like Vsync, but might cause graphical artifacts.",
		-- Layout
		layout = "LAYOUT",
		uiSkin = "UI skin:",
		fullscreenType = "Fullscreen type:",
		windowResolution = "Window resolution:",
		desktop = "Desktop",
		exclusive = "Exclusive",
		fullscreen = "Fullscreen",
		-- Details
		details = "DETAIL SETTINGS",
		backgroundVideos = "Background videos",
		backgroundImages = "Background images",
		-------------- Gameplay
		gameplay = "GAMEPLAY",
		-- Scroll speed
		scrollSpeed = "SCROLL SPEED",
		scrollSpeedType = "Speed type",
		scrollSpeedLower = "Scroll speed:",
		tempoFactor = "Tempo factor",
		tempoFactorTip = "Specifies how the BPM should affect the scroll speed.",
		average = "Average",
		primary = "Primary",
		minimum = "Minimum",
		maximum = "Maximum",
		primaryTempo = "Primary tempo:",
		constScrollSpeed = "Constant scroll speed",
		scaleScrollSpeed = "Scale scroll speed with rate",
		taikoSV = "Taiko SV",
		-- Scoring
		scoring = "SCORING",
		scoreSystem = "Score system:",
		judgement = "Judgement:",
		nearestInput = "Nearest input",
		-- Health
		health = "HEALTH",
		maxHP = "Max health:",
		actionOnFail = "Action in case of failure",
		none = "None",
		pause = "Pause",
		quit = "Quit",
		autoShift = "Auto shift",
		-- Visuals
		visuals = "VISUALS",
		-- Other
		ratingWindow = "Rating hit timing window:",
		lastMeanValues = "Last mean values:",
		-------------- Audio
		audio = "AUDIO",
		-- Volume
		volume = "VOLUME",
		master = "Master:",
		music = "Music:",
		effect = "Effect:",
		ui = "UI:",
		rateChangesPitch = "Rate changes pitch",
		rateChangesPitchTip = "Changing the speed of the music will also change the pitch of the music.",
		autoKeySound = "Auto key sound",
		autoKeySoundTip = "Hitsound will play in perfect sync with the music, no matter how early/late you press a note.",
		midiConstantVolume = "MIDI constant volume",
		muteOnUnfocus = "Minimized game mutes music",
		-- Device
		device = "DEVICE",
		updatePeriod = "Update period:",
		bufferLength = "Buffer length:",
		adjustRate = "Adjust rate:",
		apply = "Apply",
		reset = "Reset",
		-- Offset adjustment
		offsetAdjustment = "OFFSET ADJUSTMENT",
		universalOffset = "Universal offset:",
		chartFormatOffsets = "OFFSET ADJUSTMENT FOR CHART FORMATS",
		-------------- Skin
		skin = "SKIN",
		-- Skin
		currentSkin = "Current skin:",
		previewGameplay = "Preview gameplay",
		openSkinSettings = "Open skin settings",
		openCurrentSkinFolder = "Open current skin folder",
		lnShortening = "LN shortening:",
		--- Cursor
		cursor = "CURSOR",
		cursorSize = "Cursor size:",
		showTrail = "Show trail",
		trailDensity = "Trail density:",
		trailQuality = "Trail quality:",
		trailLifetime = "Trail lifetime:",
		trailStyle = "Trail style",
		vanishing = "Vanishing",
		shrinking = "Shrinking",
		-- Camera
		camera = "3D CAMERA",
		cameraControls = "Controls:\nF9 - enter camera mode.\nF10 - reset\nWASD - forward/left/right/back.\nSHIFT/SPACE - up/down.\nLeft mouse button - rotate",
		enableCamera = "Enable 3D camera",
		cameraX = "Allow rotation of X coordinate",
		cameraY = "Allow rotation of Y coordinate",
		-------------- Input
		-- Keyboard
		input = "INPUT",
		keyboard = "KEYBOARD",
		maniaLayout = "osu!mania layout",
		-- Offset adjustment
		inputOffset = "Input offset:",
		visualOffset = "Visual offset:",
		multiplyInputOffset = "Multiply input offset by rate",
		multiplyVisualOffset = "Multply input offset by rate",
		-- Other
		other = "OTHER",
		threadedInput = "Threaded input",
		threadedInputTip = "Your inputs will be processed in a separate thread, FPS will have no effect on the timings.",
		taikoNoteHandler = "2K VSRG as Taiko charts",
		taikoNoteHandlerTip = "Toggle to play taiko charts.",
		-------------- MAINTENANCE
		maintenance = "MAINTENANCE",
	},
	songSelect = {
		mappedBy = "Mapped by %s",
		from = "From %s",
		chartInfoFirstRow = "Length: %s BPM: %s Objects: %s",
		chartInfoSecondRow = "Circles: %s Sliders: %s Spinners: %s",
		chartInfoThirdRow = "Keys: %s OD: %s HP: %s Star rating: %s",
		--
		localRanking = "Local ranking",
		onlineRankin = "Online ranking",
		osuApiRanking = "osu! API ranking",
		--
		collections = "Collections",
		recent = "Recently played",
		artist = "By Artist",
		difficulty = "By Difficulty",
		noGrouping = "No grouping",
		--
		group = "Group",
		sort = "Sort",
		byCharts = "By Charts",
		byLocations = "By Locations",
		byDirectories = "By Directories",
		byId = "By ID",
		byTitle = "By Title",
		byArtist = "By Artist",
		byDifficulty = "By Difficulty",
		byLevel = "By Level",
		byDuration = "By Duration",
		byBpm = "By BPM",
		byModTime = "By Mod. time",
		bySetModTime = "By Set Mod. time",
		byLastPlayed = "By Last played",
		--
		search = "Search:",
		searchInsert = "Search (Insert):",
		typeToSearch = "Type to search!",
		noMatches = "No matches found.",
		matchesFound = "%i match(es) found.",
		noCharts = "No songs? Try clearing the search AND the filters.\nYou can drop osu!, Etterna or Quaver 'Songs' folder in the game window to add songs.\n\nDrop .osz files to import osu! beatmaps.\n\nOr add charts to `userdata/charts/my_songs`.",
	},
	playerStats = {
		sessionsInYear = "%i sessions in %s",
		sessionsTime = "Max: %i minutes / Avg: %i minutes"
	},
	scoreList = {
		score = "Score",
		hasMods = "Has mods",
		tooltip = "Achieved on %s\n%s\nAccuracy:%0.02f\nMods:%s"
	},
	chartOptionsModal = {
		title = "%s\nWhat do you want to do with this chart?",
		manageLocations = "1. Manage locations",
		exportToOsu = "2. Export to .osu",
		filters = "3. Filters",
		edit = "4. Edit",
		fileManager = "5. Open in file manager",
		cancel = "6. Cancel",
	},
	modifiersModal = {
		title = "Mods provide different ways to enjoy gameplay. Some have an effect on the score you can achieve during ranked play. Others are just for fun.",
		reset = "1. Reset all mods",
		close = "2. Close",
	},
	filtersModal = {
		title = "Filters allow you to... idk... hide charts you do not want to play. (Change later)",
		reset = "1. Reset all filters",
		close = "2. Close",
		["original input mode"] = "Original Mode",
		["actual input mode"] = "Actual Mode",
		["format (used parser)"] = "File",
		["scratch"] = "Scratch",
		["(not) played"] = "Played",
		["played"] = "Yes",
		["not played"] = "No",
		["has scratch"] = "Yes",
		["has not scratch"] = "No",
	},
	skinSettingsModal = {
		title = "Customize skin settings. What else do you expect?",
		noSettings = "No settings!",
		close = "1. Close",
	},
	inputsModal = {
		title = "Press the key/button on your keyboard/joystick for the corresponding column. Hit ESC to go back.",
	},
	locationImportModal = {
		importTitle = "Import songs from this folder? The game will only read the songs from this folder, it will not modify/copy them.",
		alreadyImported = "The game is already reading songs from this folder. Do you want to refresh the cache?",
		import = "1. Import",
		cancel = "2. Cancel",
		yes = "1. Yes",
		no = "2. No"
	},
	result = {
		chartBy = "Chart by %s",
		chartFrom = "Chart from %s",
		playedBy = "Played by %s on %s",
		mean = "Mean: %s",
		maxError = "Max error: %s",
		scrollSpeed = "Scroll speed: %s",
		mods = "Mods: %s",
		guest = "Guest",
	},
	uiLock = {
		processingCharts = "Processing charts...",
		path = "Path",
		chartsFound = "Processed / Found",
		chartsCached = "Charts cached",
	},
	gameTips = {
		handStrain = "Don't strain your hands while you play, even if the parts are really hard.",
		stamina = "Learn to conserve your stamina. This is the most important skill in rhythm games.",
		getAJob = "Get a job to improve even faster.",
		screenshot = "You can take a screenshot by pressing F12.",
		discord = "Make sure to join our discord server!",
		whining = "Whining will not help you.",
		comfortZone = "Avoid playing in your comfort zone.",
		warmUp = "Warm up is very important. You can't get good scores if you don't warm up properly.",
		lua = "Learn programming and Lua to help develop this game.",
		sessionTime = "An hour and a half is a good time for a session.",
		archLinux = "Use Arch Linux with Hyprland to become a better person.",
		fpsLimit = "Limit your FPS to 1024 or less, there is no point in setting it higher.",
		osz = "Drag and drop osu! beatmaps into game window to import them.",
		subahibi = "Read Subarashiki Hibi.",
		vsrgScrollSpeed = "26 - 30 is a good range for a scroll speed.",
		pauses = "You can pause in this game. We allow you to abuse it.",
		doubleSetup = "Double setup is allowed. Surprise: You can bind any number of keys to a column.",
		issues = "Report any issues on our discord server, we can't possibly find them all on our own.",
	},
}

l.fontFiles = {
	["ZenMaruGothic-Black"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Black.ttf",
	["ZenMaruGothic-Medium"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Medium.ttf",
	["ZenMaruGothic-Bold"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Bold.ttf",
	["ZenMaruGothic-Regular"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Regular.ttf",
	["Aller"] = "osu_ui/assets/ui_font/Aller/Aller_Rg.ttf",
	["Aller-Light"] = "osu_ui/assets/ui_font/Aller/Aller_Lt.ttf",
	["Aller-Bold"] = "osu_ui/assets/ui_font/Aller/Aller_Bd.ttf",
}

l.fontGroups = {
	misc = {
		backButton = { "Aller", 20, "ZenMaruGothic-Regular" },
		notification = { "Aller", 24, "ZenMaruGothic-Regular" },
		popup = { "Aller", 14, "ZenMaruGothic-Regular" },
		tooltip = { "Aller", 14, "ZenMaruGothic-Regular" },
	},
	mainMenu = {
		username = { "Aller", 20, "ZenMaruGothic-Regular" },
		belowUsername = { "Aller", 14 },
		rank = { "Aller-Light", 50 },
		info = { "Aller", 18, "ZenMaruGothic-Regular" },
		gameTip = { "Aller", 22, "ZenMaruGothic-Regular" },
	},
	settings = {
		optionsLabel = { "Aller-Light", 28, "ZenMaruGothic-Regular" },
		gameBehaviorLabel = { "Aller-Light", 19, "ZenMaruGothic-Regular" },
		search = { "Aller", 25, "ZenMaruGothic-Regular" },
		tabLabel = { "Aller", 33, "ZenMaruGothic-Regular" },
		groupLabel = { "Aller-Bold", 16, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 16, "ZenMaruGothic-Regular" },
		checkboxes = { "Aller", 16, "ZenMaruGothic-Regular" },
		combos = { "Aller", 16, "ZenMaruGothic-Regular" },
		sliders = { "Aller", 16, "ZenMaruGothic-Regular" },
		labels = { "Aller", 16, "ZenMaruGothic-Regular" },
	},
	songSelect = {
		chartName = { "Aller", 25, "ZenMaruGothic-Regular" },
		chartedBy = { "Aller", 16, "ZenMaruGothic-Regular" },
		infoTop = { "Aller-Bold", 16 },
		infoCenter = { "Aller", 16 },
		infoBottom = { "Aller", 12 },
		dropdown = { "Aller", 18 },
		groupSort = { "Aller-Light", 30 },
		username = { "Aller", 20, "ZenMaruGothic-Medium" },
		belowUsername = { "Aller", 14 },
		rank = { "Aller-Light", 50 },
		scrollSpeed = { "Aller-Light", 23 },
		tabs = { "Aller", 14 },
		mods = { "Aller", 41 },
		search = { "Aller-Bold", 18, "ZenMaruGothic-Bold" },
		searchMatches = { "Aller-Bold", 15 },
		noCharts = { "Aller-Bold", 30, "ZenMaruGothic-Bold" }
	},
	chartSetList = {
		title = { "Aller", 22, "ZenMaruGothic-Medium" },
		secondRow = { "Aller", 16, "ZenMaruGothic-Medium" },
		thirdRow = { "Aller-Bold", 16, "ZenMaruGothic-Medium" },
		noItems = { "Aller", 36 },
	},
	scoreList = {
		username = { "Aller-Bold", 22, "ZenMaruGothic-Medium" },
		score = { "Aller", 16 },
		rightSide = { "Aller", 14 },
		noItems = { "Aller", 36 },
	},
	chartOptionsModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
	},
	modifiersModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		mode = { "Aller-Light", 41, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
		modifierName = { "Aller-Light", 20, "ZenMaruGothic-Regular" },
		numberOfUses = { "Aller-Light", 14, "ZenMaruGothic-Regular" },
		notSelected = { "Aller", 16, "ZenMaruGothic-Regular" },
		sliders = { "Aller", 16, "ZenMaruGothic-Regular" },
		checkboxes = { "Aller", 16, "ZenMaruGothic-Regular" },
	},
	filtersModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		checkboxes = { "Aller", 16, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
		groupButtons = { "Aller", 25, "ZenMaruGothic-Regular" },
	},
	skinSettingsModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		mode = { "Aller-Light", 41, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
		noSettings = { "Aller", 24, "ZenMaruGothic-Regular" },
		noteSkinSettings = { "Aller", 24, "ZenMaruGothic-Regular" },
	},
	inputsModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		combos = { "Aller", 16, "ZenMaruGothic-Regular" },
		binds = { "Aller", 16, "ZenMaruGothic-Regular" },
	},
	locationImportModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		directory = { "Aller-Light", 41, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
	},
	result = {
		title = { "Aller-Light", 30, "ZenMaruGothic-Regular" },
		creator = { "Aller", 22, "ZenMaruGothic-Regular" },
		playInfo = { "Aller", 22, "ZenMaruGothic-Regular" },
		graphInfo = { "ZenMaruGothic-Regular", 18 },
		pp = { "ZenMaruGothic-Medium", 36 },
	},
	playerStats = {
		activity = { "Aller", 18, "ZenMaruGothic-Regular" },
		danTable = { "Aller", 20, "ZenMaruGothic-Regular" },
		dropdown = { "Aller", 18 },
		textNearDropdown = { "Aller-Light", 30 },
		username = { "Aller", 20, "ZenMaruGothic-Regular" },
		belowUsername = { "Aller", 14 },
		rank = { "Aller-Light", 50 },
		statsModeLargeText = { "Aller", 36 },
		stats = { "Aller", 24, "ZenMaruGothic-Regular" },
		modeStats = { "Aller", 21, "ZenMaruGothic-Regular" },
		headerInfo = { "Aller", 18, "ZenMaruGothic-Regular" },
		topDans = { "Aller-Light", 27 },
	},
	uiLock = {
		title = { "Aller-Bold", 48 },
		status = { "Aller", 36 },
	},
}

return l
