local l = {}

l.textGroups = {
	mainMenu = {
		chartCount = "¡Tienes %i en total de mapas!",
		sessionTime = "Duración de la sesión actual: %s",
		time = "Hora actual: %s",
		supporter = "Gracias por jugar gucci!mania!"
	},
	settings = {
		-------------- General
		general = "",
		-- Language
		language = "",
		selectLanguage = "",
		originalMetadata = "Preferir metadatos en su idioma original",
		-- Updates
		updates = "",
		autoUpdate = "",
		gitVersion = "Versión git del juego.",
		upToDate = "Tu gucci!mania está actualizado",
		notUpToDate = "No se sabe si el juego está actualizado.",
		openSoundsphereFolder = "",
		--- Main menu
		mainMenu = "",
		hideGameTips = "",
		disableIntro = "",
		--- Song select
		songSelect = "SELECTOR DE CANCIONES",
		difficultyCalculator = "Sistema de dificultad:",
		vimMotions = "Vim motions (SOLO PARA EXPERTOS)",
		previewIcon = "Icono de vista previa (solo desplaza el texto)",
		chartPreview = "Previsualización del mapa",
		backgroundDim = "Oscurecer fondo:",
		backgroundBlur = "Difuminar fondo:",
		preciseRates = "Incremento de velocidad de la música del 0,025x",
		preciseRatesTip = "Permite aumentar la velocidad de la música en 0.025x en lugar de 0.05x.",
		--- Result screen
		resultScreen = "PANTALLA DE RESULTADOS",
		showDifficultyAndRate = "Mostrar dificultad y rate",
		showHitGraph = "Mostrar gráfico de pulsaciones",
		showPP = "Mostrar PP",
		-------------- Graphics
		graphics = "",
		-- Renderer
		renderer = "",
		vsyncType = "Tipo de Vsync:",
		fpsLimit = "",
		unlimitedFps = "",
		showFPS = "",
		showProfiler = "Mostrar rendimiento",
		vsyncInSongSelect = "Vsync en el selector de canciones",
		adaptive = "",
		enabled = "",
		disabled = "",
		msaaTip = "Antialiasing. Ajusta a 2 o 4 para suavizar bordes. Requiere reiniciar el juego.",
		dwmFlushTip = "Actúa como el Vsync, pero puede causar errores gráficos",
		-- Layout
		layout = "LAYOUT",
		uiSkin = "UI skin:",
		fullscreenType = "",
		windowResolution = "Resolución:",
		desktop = "",
		exclusive = "",
		fullscreen = "",
		-- Details
		details = "",
		backgroundVideos = "",
		backgroundImages = "",
		-------------- Gameplay
		gameplay = "GAMEPLAY",
		-- Screen
		screen = "",
		screenResolution = "",
		positionX = "",
		positionY = "",
		renderAtNativeRes = "Renderizar a resolución nativa",
		-- Scroll speed
		scrollSpeed = "VELOCIDAD DE DESPLAZAMIENTO",
		scrollSpeedType = "Tipo de velocidad",
		scrollSpeedLower = "Velocidad de desplazamiento:",
		tempoFactor = "Tempo factor",
		tempoFactorTip = "Especifíca como el BPM afecta la velocidad de desplazamiento.",
		average = "Promedio",
		primary = "Primario",
		minimum = "Mínimo",
		maximum = "Máximo",
		primaryTempo = "Tempo primario:",
		constScrollSpeed = "Velocidad de desplazamiento constante",
		scaleScrollSpeed = "Sube la velocidad de desplazamiento junto al rate",
		taikoSV = "Taiko SV",
		-- Scoring
		scoring = "PUNTUACIÓN",
		scoreSystem = "Sistema de puntuación:",
		judgement = "Juicio:",
		nearestInput = "Input mas cercano",
		-- Health
		health = "SALUD",
		maxHP = "Salud maxima:",
		actionOnFail = "Acción en caso de fallar",
		none = "Ninguna",
		pause = "Pausar",
		quit = "Salir",
		autoShift = "Desplazamiento automático",
		-- Visuals
		visuals = "VISUALES",
		-- Other
		ratingWindow = "Rating hit timing window:",
		lastMeanValues = "Last mean values:",
		-------------- Audio
		audio = "AUDIO",
		-- Volume
		volume = "VOLUMEN",
		master = "Master:",
		music = "Música:",
		effect = "Efectos:",
		ui = "UI:",
		rateChangesPitch = "El rate cambia el pitch",
		rateChangesPitchTip = "Cambiando la velocidad de la música también cambiará el pitch de la música.",
		autoKeySound = "Sonido automático de tecla",
		autoKeySoundTip = "El sonido de la tecla se reproducirá en perfecta sincronización con la música, sin importar si presionas una nota antes o después.",
		midiConstantVolume = "Volumen constante de MIDI",
		muteOnUnfocus = "El juego minimizado silencia la música",
		-- Device
		device = "DISPOSITIVO",
		updatePeriod = "Período de \nactualización:",
		bufferLength = "Longitud del \nbúfer:",
		adjustRate = "Tasa de ajuste:",
		apply = "Aplicar",
		reset = "Restablecer",
		-- Offset adjustment
		offsetAdjustment = "AJUSTE DE OFFSET",
		universalOffset = "Offset universal:",
		chartFormatOffsets = "Ajuste de Offset para distintos tipos de mapas",
		-------------- Skin
		skin = "SKIN",
		-- Skin
		currentSkin = "Skin actual:",
		previewGameplay = "Previsualizar Gameplay",
		openSkinSettings = "Abrir configuración de skin",
		openCurrentSkinFolder = "Abrir carpeta de skin actual",
		lnShortening = "Acortar LN (Percy):",
		--- Cursor
		cursor = "CURSOR",
		cursorSize = "Tamaño del \nCursor:\n",
		showTrail = "Mostrar estela\n",
		trailDensity = "Densidad de la \nestela:\n",
		trailQuality = "Calidad de la \nestela:\n",
		trailLifetime = "Duración de la \nestela:\n",
		trailStyle = "Estilo de la estela",
		vanishing = "Desvanecimiento",
		shrinking = "Encogimiento",
		-- Camera
		camera = "Cámara 3D",
		cameraControls = "Controles:\nF9 - entrar en modo cámara.\nF10 - restablecer\nWASD - adelante/izquierda/derecha/atrás.\nSHIFT/ESPACIO - arriba/abajo.\nBotón izquierdo del ratón - rotar",
		enableCamera = "Habilitar cámara 3D",
		cameraX = "Permitir rotación en el eje X",
		cameraY = "Permitir rotación en el eje Y",
		-------------- Input
		-- Keyboard
		input = "",
		keyboard = "TECLADO",
		maniaLayout = "Disposición de teclas en Osu!mania",
		-- Offset adjustment
		inputOffset = "Offset de \nentrada:",
		visualOffset = "Offset visual:",
		multiplyInputOffset = "Multiplicar offset de entrada por la velocidad",
		multiplyVisualOffset = "Multiplicar offset visual por la velocidad",
		-- Other
		other = "OTHER",
		threadedInput = "Entrada en hilos",
		threadedInputTip = "Tus entradas serán procesadas en un hilo separado, los FPS no tendrán efecto en los tiempos.",
		taikoNoteHandler = "2K VSRG como Mapas Taiko",
		taikoNoteHandlerTip = "Alternan para jugar Mapas de Taiko.",
		-------------- MAINTENANCE
		maintenance = "",
	},
	songSelect = {
		mappedBy = "Mapeado por %s",
		from = "Desde %s",
		chartInfoFirstRow = "Duración: %s BPM: %s Objetos: %s",
		chartInfoSecondRow = "Círculos: %s Deslizadores: %s Spinners: %s",
		chartInfoThirdRow = "Keys: %s OD: %s HP: %s Dificultad: %s",
		--
		localRanking = "Ranking local",
		onlineRankin = "Ranking online",
		osuApiRanking = "osu! API ranking",
		--
		collections = "Colecciones",
		recent = "Jugadas recientes",
		artist = "Por artista",
		difficulty = "Por dificultad",
		noGrouping = "Sin grupo",
		--
		group = "Grupo",
		sort = "Ordenar",
		byCharts = "Por Mapas",
		byLocations = "Por la Localización",
		byDirectories = "Por el Directorio",
		byId = "Por ID",
		byTitle = "Por Titulo",
		byArtist = "Por Artista",
		byDifficulty = "Por Dificultad",
		byLevel = "Por Titulo",
		byDuration = "Por Duración",
		byBpm = "Por BPM",
		byModTime = "Por Fecha de adición ",
		bySetModTime = "By Set Mod. time",
		byLastPlayed = "Recién jugados",
		--
		search = "Buscar:",
		searchInsert = "Buscar: (Insert):",
		typeToSearch = "Escribe para buscar!",
		noMatches = "No se encontraron resultados.",
		matchesFound = "%i resultado(s) encontrados.",
		noCharts = "Si no hay canciones? Intenta limpiar la búsqueda Y los filtros.\nPuedes arrastrar la carpeta de 'Songs' de osu!, Etterna o Quaver en la ventana del juego para añadir canciones.\n\nSuelta archivos .osz para importar beatmaps de osu!.\n\nO añade mapas a userdata/charts/my_songs.",
	},
	playerStats = {
		sessionsInYear = "%i Sesiones en %s",
		sessionsTime = "Max: %i minutos / Avg: %i minutos"
	},
	firstTimeSetup = {
		underLogo = "Puedes permitir que gucci!mania use canciones y skins de otros juegos.\nEl juego solo leerá archivos de estas carpetas, no se copiará nada.",
		useOsuSongs = "Usar beatmaps de la carpeta de osu!",
		useEtternaSongs = "Usar canciones de la carpeta de Etterna.",
		useQuaverSongs = "Usar canciones de la carpeta de Quaver.",
		useOsuSkins = "Usar skins de la carpeta de osu!",
		applyOsuSettings = "Aplicar configuraciones de osu! (velocidad de desplazamiento, skin, etc...).",
		done = "Listo",
		goodbye = "Todas las opciones seleccionadas han sido aplicadas.\n¡Buena suerte jugando el juego!",
		start = "Empezar",
		chartsFound = "Procesado / Encontrado",
		chartsCached = "Canciones en caché",
		path = "Ruta",
		warning = "NO CIERRES EL JUEGO! Procesar canciones lleva tiempo, puedes minimizar el juego."
	},
	scoreList = {
		score = "Score",
		hasMods = "Tiene Mods",
		tooltip = "Logrado el %s\n%s\nPrecisión:%0.02f\nMods:%s"
	},
	chartOptionsModal = {
		title = "%s\n¿Qué quieres hacer con este mapa?",
		manageLocations = "1. Gestionar ubicaciones",
		exportToOsu = "2. Exportar a .osu",
		filters = "3. Filtros",
		edit = "4. Editar",
		fileManager = "5. Abrir en el gestor de archivos",
		cancel = "6. Cancelar",
	},
	modifiersModal = {
		title = "Los mods ofrecen diferentes maneras de disfrutar del juego. Algunos afectan la puntuación que puedes lograr durante el juego clasificado. Otros son solo para divertirse.",
		reset = "1. Reiniciar todos los Mods",
		close = "2. Cerrar",
	},
	filtersModal = {
		title = "Los Filtros sirven para buscar mapas en función de ciertas características.",
		reset = "1. Reiniciar todos los Filtros",
		close = "2. Cerrar",
		["original input mode"] = "Modo Original",
		["actual input mode"] = "Modo Actual",
		["format (used parser)"] = "Archivo",
		["scratch"] = "Scratch",
		["(not) played"] = "Jugado",
		["played"] = "Si",
		["not played"] = "No",
		["has scratch"] = "Si",
		["has not scratch"] = "No",
	},
	skinSettingsModal = {
		title = "Personalizar Ajustes de la Skin",
		noSettings = "Sin Ajustes!",
		close = "1. Cerrar",
	},
	inputsModal = {
		title = "Presiona la tecla/botón en tu teclado/joystick para la columna correspondiente. Pulsa ESC para regresar.",
	},
	locationImportModal = {
		importTitle = "¿Importar canciones desde esta carpeta? El juego solo leerá las canciones de esta carpeta, no las modificará ni copiará.",
		alreadyImported = "El juego ya está leyendo canciones desde esta carpeta. ¿Quieres actualizar la caché?",
		import = "1. Importar",
		cancel = "2. Cancelar",
		yes = "1. Si",
		no = "2. No"
	},
	result = {
		chartBy = "Mapa por %s",
		chartFrom = "Mapa de %s",
		playedBy = "Jugado por %s el %s",
		mean = "Mean: %s",
		maxError = "Max error: %s",
		scrollSpeed = "Velocidad de Desplazamiento: %s",
		mods = "Mods: %s",
		guest = "Invitado",
	},
	uiLock = {
		processingCharts = "Procesando Mapas...",
		path = "Ruta",
		chartsFound = "Procesado / Encontrado",
		chartsCached = "Mapas en caché",
	},
	gameTips = {
		handStrain = "No esfuerces tus manos mientras juegas, incluso si las partes son realmente difíciles.",
		stamina = "Aprende a conservar tu resistencia. Esta es la habilidad más importante en los juegos de ritmo.",
		getAJob = "Consigue un trabajo para mejorar aún más rápido.",
		screenshot = "Puedes tomar una captura de pantalla presionando F12.",
		discord = "¡Asegúrate de unirte a nuestro servidor de Discord!",
		whining = "Quejarte no te ayudará.",
		comfortZone = "Evita jugar en tu zona de confort.",
		warmUp = "El calentamiento es muy importante. No puedes obtener buenas puntuaciones si no calientas adecuadamente. ¡No querrás lesionarte!",
		lua = "Aprende programación y Lua para ayudar a desarrollar este juego.",
		sessionTime = "Una hora y media es un buen tiempo para una sesión",
		archLinux = "Usa Arch Linux con Hyprland para convertirte en una mejor persona.",
		fpsLimit = "Limita tus FPS a 1024 o menos, no tiene sentido configurarlo más alto.",
		osz = "Arrastra y suelta los beatmaps de osu! en la ventana del juego para importarlos.",
		subahibi = "Lee Subarashiki Hibi.",
		vsrgScrollSpeed = "26 - 30 es un buen rango para la velocidad de desplazamiento.",
		pauses = "Puedes pausar en este juego. Te permitimos abusar de ello.",
		doubleSetup = "Se permite la configuración doble. Sorpresa: Puedes asignar cualquier número de teclas a una columna.",
		issues = "Reporta cualquier problema en nuestro servidor de Discord, no podemos encontrarlos todos por nuestra cuenta.",
	},
}

l.fontFiles = {
	["ZenMaruGothic-Black"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Black.ttf",
	["ZenMaruGothic-Medium"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Medium.ttf",
	["ZenMaruGothic-Bold"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Bold.ttf",
	["ZenMaruGothic-Regular"] = "osu_ui/assets/ui_font/ZenMaruGothic/ZenMaruGothic-Regular.ttf",
	["Aller"] = "osu_ui/assets/ui_font/Aller/Aller_Rg.ttf",
	["Aller-Light"] = "osu_ui/assets/ui_font/Aller/Aller_Lt.ttf",
	["Aller-Bold"] = "osu_ui/assets/ui_font/Aller/Aller_Bd.ttf",
}

l.fontGroups = {
	misc = {
		backButton = { "Aller", 20, "ZenMaruGothic-Regular" },
		notification = { "Aller", 24, "ZenMaruGothic-Regular" },
		popup = { "Aller", 14, "ZenMaruGothic-Regular" },
		tooltip = { "Aller", 14, "ZenMaruGothic-Regular" },
	},
	mainMenu = {
		username = { "Aller", 20, "ZenMaruGothic-Regular" },
		belowUsername = { "Aller", 14 },
		rank = { "Aller-Light", 50 },
		info = { "Aller", 18, "ZenMaruGothic-Regular" },
		gameTip = { "Aller", 22, "ZenMaruGothic-Regular" },
	},
	settings = {
		optionsLabel = { "Aller-Light", 28, "ZenMaruGothic-Regular" },
		gameBehaviorLabel = { "Aller-Light", 19, "ZenMaruGothic-Regular" },
		search = { "Aller", 25, "ZenMaruGothic-Regular" },
		tabLabel = { "Aller", 33, "ZenMaruGothic-Regular" },
		groupLabel = { "Aller-Bold", 16, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 16, "ZenMaruGothic-Regular" },
		checkboxes = { "Aller", 16, "ZenMaruGothic-Regular" },
		combos = { "Aller", 16, "ZenMaruGothic-Regular" },
		sliders = { "Aller", 16, "ZenMaruGothic-Regular" },
		labels = { "Aller", 16, "ZenMaruGothic-Regular" },
	},
	songSelect = {
		chartName = { "Aller", 25, "ZenMaruGothic-Regular" },
		chartedBy = { "Aller", 16, "ZenMaruGothic-Regular" },
		infoTop = { "Aller-Bold", 16 },
		infoCenter = { "Aller", 16 },
		infoBottom = { "Aller", 12 },
		dropdown = { "Aller", 18 },
		groupSort = { "Aller-Light", 30 },
		username = { "Aller", 20, "ZenMaruGothic-Medium" },
		belowUsername = { "Aller", 14 },
		rank = { "Aller-Light", 50 },
		scrollSpeed = { "Aller-Light", 23 },
		tabs = { "Aller", 14 },
		mods = { "Aller", 41 },
		search = { "Aller-Bold", 18, "ZenMaruGothic-Bold" },
		searchMatches = { "Aller-Bold", 15 },
		noCharts = { "Aller-Bold", 30, "ZenMaruGothic-Bold" }
	},
	chartSetList = {
		title = { "Aller", 22, "ZenMaruGothic-Medium" },
		secondRow = { "Aller", 16, "ZenMaruGothic-Medium" },
		thirdRow = { "Aller-Bold", 16, "ZenMaruGothic-Medium" },
		noItems = { "Aller", 36 },
	},
	scoreList = {
		username = { "Aller-Bold", 22, "ZenMaruGothic-Medium" },
		score = { "Aller", 16 },
		rightSide = { "Aller", 14 },
		noItems = { "Aller", 36 },
	},
	chartOptionsModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
	},
	modifiersModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		mode = { "Aller-Light", 41, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
		modifierName = { "Aller-Light", 20, "ZenMaruGothic-Regular" },
		numberOfUses = { "Aller-Light", 14, "ZenMaruGothic-Regular" },
		notSelected = { "Aller", 16, "ZenMaruGothic-Regular" },
		sliders = { "Aller", 16, "ZenMaruGothic-Regular" },
		checkboxes = { "Aller", 16, "ZenMaruGothic-Regular" },
	},
	filtersModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		checkboxes = { "Aller", 16, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
		groupButtons = { "Aller", 25, "ZenMaruGothic-Regular" },
	},
	skinSettingsModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		mode = { "Aller-Light", 41, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
		noSettings = { "Aller", 24, "ZenMaruGothic-Regular" },
		noteSkinSettings = { "Aller", 24, "ZenMaruGothic-Regular" },
	},
	inputsModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		combos = { "Aller", 16, "ZenMaruGothic-Regular" },
		binds = { "Aller", 16, "ZenMaruGothic-Regular" },
	},
	locationImportModal = {
		title = { "Aller-Light", 33, "ZenMaruGothic-Regular" },
		directory = { "Aller-Light", 41, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
	},
	result = {
		title = { "Aller-Light", 30, "ZenMaruGothic-Regular" },
		creator = { "Aller", 22, "ZenMaruGothic-Regular" },
		playInfo = { "Aller", 22, "ZenMaruGothic-Regular" },
		graphInfo = { "ZenMaruGothic-Regular", 18 },
		pp = { "ZenMaruGothic-Medium", 36 },
	},
	playerStats = {
		activity = { "Aller", 18, "ZenMaruGothic-Regular" },
		danTable = { "Aller", 20, "ZenMaruGothic-Regular" },
		dropdown = { "Aller", 18 },
		textNearDropdown = { "Aller-Light", 30 },
		username = { "Aller", 20, "ZenMaruGothic-Regular" },
		belowUsername = { "Aller", 14 },
		rank = { "Aller-Light", 50 },
		statsModeLargeText = { "Aller", 36 },
		stats = { "Aller", 24, "ZenMaruGothic-Regular" },
		modeStats = { "Aller", 21, "ZenMaruGothic-Regular" },
		headerInfo = { "Aller", 18, "ZenMaruGothic-Regular" },
		topDans = { "Aller-Light", 27 },
	},
	firstTimeSetup = {
		checkboxes = { "Aller", 16, "ZenMaruGothic-Regular" },
		combos = { "Aller", 16, "ZenMaruGothic-Regular" },
		buttons = { "Aller", 42, "ZenMaruGothic-Regular" },
		info = { "Aller", 24 },
		status = { "Aller", 36 },
		warning = { "Aller", 18 }

	},
	uiLock = {
		title = { "Aller-Bold", 48 },
		status = { "Aller", 36 },
	},
}

return l
